baseURL = "https://amin0g.github.io/"
languageCode = 'en-us'
title = "Amin Gholami's Personal Website"
theme = "LoveIt"
name = "Amin Gholami"

[params]
  author = "Amin Gholami"
  email = "a.gholami.ee@gmail.com"
  linkedin = "https://www.linkedin.com/in/amin-gholami-4862bb79"
  education = "Ph.D. in Operations Research, Minor in Mathematics, Georgia Institute of Technology (Georgia Tech)"
  description = "Senior Data Scientist – Walmart Global Tech, Sunnyvale, CA, USA"
  avatar = "avatar_amin.jpg"

